# -*- coding: utf-8 -*-
{
    'name': 'Pusat Training Indonesia',
    'summary': 'Ini adalah applikasi untuk Pusat Training Indonesia',
    'version': '1.001',
    'category': 'custom',
    'author': 'jeki',
    'maintainer': 'jeki',
    'website':  'odooindonesia.com',
    'license': 'AGPL-3',
    'data': [
        'views/peserta/profile.xml',
        'views/peserta/profile_edit.xml',
        'views/peserta/profile_edit_corporat.xml',
        'views/peserta/login.xml',
        'views/peserta/logout.xml',
        'views/peserta/password_reset.xml',
        'views/peserta/password_otp.xml',
        'views/peserta/password_new.xml',
        'views/peserta/registrasi_personal.xml',
        'views/peserta/registrasi_corporat.xml',
        'views/peserta/registrasi_done.xml',
        'views/peserta/training.xml',
        'views/peserta/training_detail.xml',
        'views/peserta/corporat_member_list.xml',
        'views/peserta/corporat_member_add.xml',
        'views/peserta/corporat_member_delete.xml',
        'views/peserta/corporat_pic.xml',
        'views/peserta/kelas.xml',
        'views/peserta/training_daftar_corporat.xml',
        'views/peserta/training_daftar_personal.xml',
        'views/peserta/dashboard.xml',
        'views/peserta/pembayaran_konfirmasi.xml',
        'views/peserta/pembayaran_done.xml',
        'views/bki_dashboard.xml',
    ],
    'application': True,
    'depends': [
        'web'
    ],
    'assets': {
        'web.assets_backend': [
            'otraining/static/src/components/**/*.js',
            'otraining/static/src/components/**/*.xml',
            'otraining/static/src/components/**/*.scss',
        ],
    },
}